// <auto-generated />
using System;
using Kollegeni.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kollegeni.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20250509074719_tt")]
    partial class tt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kollegeni.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attribute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Kollegeni.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResidencyId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResidencyId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2025, 5, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidencyId = 1,
                            RoomId = 1,
                            StartTime = new DateTime(2025, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2025, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidencyId = 1,
                            RoomId = 2,
                            StartTime = new DateTime(2025, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2025, 5, 12, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidencyId = 2,
                            RoomId = 1,
                            StartTime = new DateTime(2025, 5, 12, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kollegeni.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidencyId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Kollegeni.Models.Residency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Residencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "71, 2"
                        },
                        new
                        {
                            Id = 2,
                            Address = "74, 5"
                        });
                });

            modelBuilder.Entity("Kollegeni.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The bar room i guess",
                            Name = "Bar Room"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Room for playing Pool obviously",
                            Name = "Pool Room"
                        });
                });

            modelBuilder.Entity("Kollegeni.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "http://example.com/avatar1.jpg",
                            Email = "john@example.com",
                            Language = "English",
                            Name = "John",
                            Password = "123",
                            Username = "John"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "http://example.com/avatar2.jpg",
                            Email = "jane@example.com",
                            Language = "English",
                            Name = "Jane",
                            Password = "123",
                            Username = "JaneSmith"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "http://example.com/avatar2.jpg",
                            Email = "karen@example.com",
                            Language = "English",
                            Name = "Karen",
                            Password = "123",
                            Username = "Karen"
                        });
                });

            modelBuilder.Entity("Kollegeni.Models.UserResidence", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ResidenceId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("UserResidencies");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ResidenceId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ResidenceId = 1
                        },
                        new
                        {
                            UserId = 3,
                            ResidenceId = 2
                        });
                });

            modelBuilder.Entity("Kollegeni.Models.Booking", b =>
                {
                    b.HasOne("Kollegeni.Models.Residency", "Residency")
                        .WithMany("Bookings")
                        .HasForeignKey("ResidencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kollegeni.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residency");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Kollegeni.Models.Event", b =>
                {
                    b.HasOne("Kollegeni.Models.Residency", "Residency")
                        .WithMany("Events")
                        .HasForeignKey("ResidencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residency");
                });

            modelBuilder.Entity("Kollegeni.Models.Residency", b =>
                {
                    b.HasOne("Kollegeni.Models.Admin", null)
                        .WithMany("ManagedResidencies")
                        .HasForeignKey("AdminId");
                });

            modelBuilder.Entity("Kollegeni.Models.UserResidence", b =>
                {
                    b.HasOne("Kollegeni.Models.Residency", "Residency")
                        .WithMany("UserResidencies")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kollegeni.Models.User", "User")
                        .WithMany("UserResidences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kollegeni.Models.Admin", b =>
                {
                    b.Navigation("ManagedResidencies");
                });

            modelBuilder.Entity("Kollegeni.Models.Residency", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Events");

                    b.Navigation("UserResidencies");
                });

            modelBuilder.Entity("Kollegeni.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Kollegeni.Models.User", b =>
                {
                    b.Navigation("UserResidences");
                });
#pragma warning restore 612, 618
        }
    }
}
